# om namah shivaya

service: site
runtime: nodejs14
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.90
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
  - url: /
    static_dir: build
    secure: always
    redirect_http_response_code: 301
env_variables:
  NODE_ENV: 'development'
