# om namah shivaya

service: site
runtime: nodejs14
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.90
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg|html))$
    static_files: build/\1
    upload: build/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg|html)$
