# om namah shivaya

steps:
  # npm install
  - name: node
    entrypoint: npm
    args: ['install']

  # npm run build
  - name: node
    entrypoint: npm
    args: ['run', 'build']

  # deploy the service
  - name: gcr.io/cloud-builders/gcloud
    args: ['app', 'deploy']
