steps:
  # npm install
  - name: node:20.11.0
    entrypoint: yarn
    args: ["install"]

  # npm run build
  - name: node:20.11.0
    entrypoint: yarn
    args: ["build"]
    env:
      - "NODE_ENV=development"
      - "SKIP_PREFLIGHT_CHECK=true"
      - "REACT_APP_STRIPE_CLIENT_KEY=pk_test_51JcD2bBdk22npNeJQBWoPOP8JMvOlhYFkCr9KB5YlxU9vtV7Amdkl3lVLxX0qWxXy3YmghTewaILVISoURTfY8YJ00VvhyCojd"
      - "REACT_APP_ENDPOINT=https://dev.graphql.romingo.com/graphql"
      - "REACT_APP_MUI_LICENSE=362ba15d1302d65b235b27fb1249c342Tz02NzMxMCxFPTE3MTY2Njc0NjkwMTAsUz1wcm8sTE09c3Vic2NyaXB0aW9uLEtWPTI="
      - "REACT_APP_GOOGLE_MAPS_API_KEY=AIzaSyDZAHqC_b5YOl00aj2LRivjvm0tNyxkZcI"
      - "TSC_COMPILE_ON_ERROR=true"
  # deploy the service
  - name: gcr.io/cloud-builders/gcloud
    args: ["app", "deploy", "--appyaml", "app.dev.yaml"]
timeout: 2020s
