steps:
  # npm install
  - name: node:20.11.0
    entrypoint: yarn
    args: ["install"]

  # npm run build
  - name: node:20.11.0
    entrypoint: yarn
    args: ["build"]
    env:
      - "NODE_ENV=production"
      - "REACT_APP_STRIPE_CLIENT_KEY=pk_live_51JcD2bBdk22npNeJXwmOgLZHOjxH2CK0SiDljaSeByUGjUfAE0CfpOvY3nTwCX0OE8cShJd51ICyJ8V9T3W6YoXE00JBuV4MWW"
      - "REACT_APP_ENDPOINT=https://graphql.romingo.com/graphql"
      - "REACT_APP_BASE_ENDPOINT=https://graphql.romingo.com/"
      - "SKIP_PREFLIGHT_CHECK=true"
      - "REACT_APP_MUI_LICENSE=362ba15d1302d65b235b27fb1249c342Tz02NzMxMCxFPTE3MTY2Njc0NjkwMTAsUz1wcm8sTE09c3Vic2NyaXB0aW9uLEtWPTI="
  # deploy the service
  - name: gcr.io/cloud-builders/gcloud
    args: ["app", "deploy", "--appyaml", "app.prod.yaml"]
timeout: 2020s
