export const SAVE_SEARCH = "SAVE_SEARCH"
export const REMOVE_SEARCH = "REMOVE_SEARCH"
export const SET_AUTHENTICATED="SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED="SET_UNAUTHENTICATED";
export const SET_USER="SET_USER";